apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.5
          env:
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KEYCLOAK_ADMIN
              value: "god"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "Kami"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: "postgres-service"
            - name: KC_DB_URL_DATABASE
              value: "keycloak"
            - name: KC_DB_USERNAME
              value: "keycloak"
            - name: KC_DB_PASSWORD
              value: "kaminarinokokyu"
            - name: KC_SSL_REQUIRED
              value: "None"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME
              value: "team7.launchingkube.com"
            - name: KC_HOSTNAME_URL
              value: "https://team7.launchingkube.com"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "true"
          ports:
            - containerPort: 8180
            - containerPort: 9000
          args:
            - "start"
            - "--http-port=8180"
            - "--import-realm"
            - "--verbose"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
    - port: 8180
      targetPort: 8180
  type: ClusterIP
