name: team7-monopoly
services:
  frontend:
    image: registry.gitlab.com/kdg-ti/integratieproject-2/2024-2025/team7/frontendimagelocal:latest
    container_name: frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
      - VITE_KC_URL=http://localhost:8180
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
  backend:
    image: registry.gitlab.com/kdg-ti/integratieproject-2/2024-2025/team7/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/monopolydb
      - SPRING_DATASOURCE_USERNAME=monopolysuper
      - SPRING_DATASOURCE_PASSWORD=234hheaaefzEzqz#
      - CORS_PORT=http://localhost:80
    depends_on:
      - db
    networks:
      - app_network

  chatbot:
    image: registry.gitlab.com/kdg-ti/integratieproject-2/2024-2025/team7/backend-ai-service/chatbot
    container_name: chatbot
    ports:
      - "8081:8081"
    environment:
      - FLASK_APP=chatbot.py
      - FLASK_RUN_PORT=8081

  prediction:
    image: registry.gitlab.com/kdg-ti/integratieproject-2/2024-2025/team7/backend-ai-service/prediction
    container_name: prediction
    ports:
      - "5000:8080"

  db:
    image: postgres:15.8-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: monopolysuper
      POSTGRES_PASSWORD: 234hheaaefzEzqz#
      POSTGRES_DB: monopolydb
    ports:
      - "54328:5432"
    networks:
      - app_network

  monopoly_idp_postgres:
    image: registry.gitlab.com/kdg-ti/integratieproject-2/2024-2025/team7/keycloak:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: kaminarinokokyu
    networks:
      - kc

  monopoly_idp_keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    environment:
      - KEYCLOAK_ADMIN=god
      - KEYCLOAK_ADMIN_PASSWORD=Kami
      - KC_DB=postgres
      - KC_DB_URL_HOST=monopoly_idp_postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=kaminarinokokyu
      - KC_SSL_REQUIRED=none
    command: start-dev
    ports:
      - "8180:8080"
    depends_on:
      - monopoly_idp_postgres
    networks:
      - kc
networks:
  app_network:
    driver: bridge
  kc:
    driver: bridge